### ISSUE TITLE
--goto problem

### ISSUE THREAD

**Issue by xmulara** [rkorzen/mbtools#1]
Przy takiej składni:
Q S A1 Proszę powiedzieć, czy weźmie Pan(i) udział w głosowaniu w wyborach parlamentarnych?
4 Na pewno nie wezmę udziału w wyborach --goto: A4_p
97 Jeszcze nie wiem / trudno powiedzieć

Q L info sdfsdfsdfsdfsdfsdffsddsfsd

Na stronie info_p wstawia precode, ale niestety w kafeterii A1 zostawia dopisane --goto: A4_p

**Comment by rkorzen** [comment]
This issue was moved to rkorzen/KreaturaParser#6
