### ISSUE TITLE
--hide problem whith 2 conditions

### ISSUE THREAD

**Issue by xmulara** [rkorzen/mbtools#2]
Q S A3 Na jakie ugrupowanie wówczas oddał(a)by Pan(i) swój głos?
1 Prawo i Sprawiedliwość / Polska Razem / Solidarna Polska --hide:$A2:{0}=="1" || $A2a:{0}=="1"
2 Platforma Obywatelska
3 Partia 'Razem'

Nie działa taki zapis **hide dla dwóch warunków**. Przy jednym jak poniżej jest już ok.

*Q S A3 Na jakie ugrupowanie wówczas oddał(a)by Pan(i) swój głos?
1 Prawo i Sprawiedliwość / Polska Razem / Solidarna Polska --hide:$A2:{0}=="1"
2 Platforma Obywatelska
3 Partia 'Razem'*

**Comment by rkorzen** [comment]
This issue was moved to rkorzen/KreaturaParser#7
